### PR TITLE
Utilities to work with parseSimpleArray/string conversion methods

### PR DESCRIPTION
**Pull request by jetelain**
This PR adds methods to serialize/de-serialize data to work with parseSimpleArray/string conversion methods of game engine.
This can be useful to create extensions, or parse logs.

### CODE REVIEW

**Comment by Braini01** [comment]
Thx for further contributions. Just one remark: Do you think it makes sense to add BIS.TXT as a namespace? Dont really feel that TXT files are a particular BIS file format. I think your code would be best suited in Utils or BIS.Core. What do you think?

**Comment by jetelain** [comment]
I was hesitating. You are right, it does not make sense.
I think it will be better in BIS.Core like config, in a "Serialization" namespace. What do you think ?

**Comment by Braini01** [comment]
Yeah, I also think it is closely related to Configs so it could go there.

**Comment by Braini01** [comment]
LGTM! Shall I merge or are you still working on it?

**Comment by jetelain** [comment]
Yes, you can merge it

**Pull request merged**
